function mergeTable(postfix, outputFile)
    % Merge tables generated by compareAll
    % postfix, postfix of input csv files
    % outputFile, output csv file name
    % Example:
    %       mergeTable('X-Ray_Block_0.05', 'X-Ray_Block.csv')
    % read bin
    A = {'ARG', 'ASN', 'ASP', 'CYS', 'GLU', 'GLN', 'HIS', 'ILE', 'LEU', 'LYS', 'MET', 'PHE', 'PRO', 'SER', 'THR', 'TRP', 'TYR', 'VAL'}
    fileName = fullfile('ARG', strcat('ARG', '_', postfix, '.csv'))
    m = csvread(fileName);
    m = m(:, 1);
    
    % read the npdf, which is the second column
    for i = 1:size(nameList, 2)
        fileName = fullfile(nameList{i}, strcat(nameList{i}, '_', postfix, '.csv'));
        temp = csvread(fileName);
        m = [m temp(:, 2)];
    end
    
    % write into a csv file
    csvwrite(outputFile, m);
end